language: ruby
rvm:
    - 2.0.0-p451
before_script:
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - mysql -e 'create database cubbyhole_test;'
    - 'npm install -g bower'
    - 'bower install'
env:
  global:
    - secure: "QmMV1ULbfxTH/puF5hSTrQK62nxzF8nvZW4j4c/gdJgyEyAUiilKG95sAXjR7yfJUS9PQqCeJFpIB6jv5f9fY++/TX/O4Qj2a8Tv0a/+RR/Wv0PwLOwg98sgEhrxcFVuZU00cRUdYlq1CabRgbEqiX4LTLKag6ze5PpDtIQejj0="
    - secure: "dAYq1uhd4n7vvkyVoWRSBeET5HKanisylUOxGwg5cK7XIkql8A1o9lRIx4XQgHXM47KQFty3tmFgTvNIzqbyNVuyq3l9/ki2CfaNd8FAgZ6dxgDX6y8e/WSOiPcrn6pgHPrbdr5Sb6S6CctFb2BFXJrU7g9cZKPBXRRKgUYeHa8="
    - secure: "A9YSdbQZxUF0+46svoNTx5bMYMh7lxNqHpl/kPX86EWEAf1z+yt5mhurq3claxs5sU3TyS8D9td6EoYzwWgUwGBHu41fTDWq4CcHbefg+WnoKpzYPf5zAEB2BkLqeD4Jf+IU1KE3PO1d7cxuZ24WB9e1ynRkJhIy5YB8jchPzqY="
    - secure: "fq7guEZjbvprgYgvVrfPhE4KRGZtPwTbnkfAFKIn9wtSdowouKK6iXU0bkqz5RCl3M+Fp17C9+wGW7XH3W2gHBFgnx4dicatoq7g6+TBUPxSrTP1uLnydpYcYvzA7GwHCCdH4FkN72JmMKZQ3BREnHDLndyigkSpSKi6edkX/Hw="
    - secure: "Nfqy6atLy5bwle8J6YkyCdoi7VJtViIo4Dx1U14F0z/dx8cF8EIHn3ptYgvsjgsaxcsq4SaZ/URIVdWGRFpNPPiLTPcdiZD3ZdJQMDTQycrpDaSWYUzrkjcgrx8/WdhIWmbqIq6dXYNXAo6c1ual3TIR5lsExkQF7+PnKwvWDq8="
    - secure: "YoK7mq0mSTOuL63uiEOc5Gceby1RukAqoRpfNXpv7ETxg80tRimLDzQdEcmBZB1fGbdd+kht4h7QYGHC+lLR0qz7lHsTtU0ncpS0Z+0cpVH1DGDu++syqPndL2pWivhN13X5umfxnBZzUKRGoj0+dm5pWcYSu9QZZtNSNzQbzMQ="
