common_settings: &common_settings
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  encoding: utf8

development:
  <<: *common_settings
  database: cubbyhole_development
  username: root
  password: root

test:
  <<: *common_settings
  database: cubbyhole_test
  prepared_statements: false
  username: travis
