common_settings: &common_settings
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *common_settings
  database: cubbyhole_development

test:
  <<: *common_settings
  database: cubbyhole_test
  prepared_statements: false
